# Which agentic-lib workflow schedule should be used?
schedule: schedule-1
# How many features should exist concurrently open for issue creation.
featuresWipLimit: 2
# TODO: Separate the concept of features in development and features in maintenance.
# How many issues should be open to be picked up?
featureDevelopmentIssuesWipLimit: 3
maintenanceIssuesWipLimit: 2
# How many attempts should be made to work on an issue?
attemptsPerBranch: 2
attemptsPerIssue: 2
