# Which agentic-lib workflow schedule should be used?
schedule: schedule-1

# Mapping for read-only filepaths, read access by agentic-lib workflows.
readOnlyFilepaths:
  mission:        "MISSION.md"
  contributing:   "CONTRIBUTING.md"
  dependencies:   "package.json"
  readme:         "README.md"
  formattingFile: ".prettierrc"
  lintingFile:    "eslint.config.js"

# Mapping for writeable filepaths, read access by agentic-lib workflows and also automated changes may be made in these paths.
writeableFilepaths:
  sources:  "elaborator-sandbox/SOURCES.md"
  library:  "elaborator-sandbox/library/"
  features: "engineer-sandbox/features/"
  src:      "engineer-sandbox/source/"
  tests:    "engineer-sandbox/tests/"
  docs:     "engineer-sandbox/docs/"

# Execution commands
buildScript: "npm run build"
testScript: "npm test"
mainScript: "npm run start"

# How many sources should exist for document fetching?
sourcesLimit: 16

# How many documents should exist in the library?
documentsLimit: 8

# How many features should exist concurrently open for issue creation?
featuresWipLimit: 3

# TODO: Separate the concept of features in development and features in maintenance.
# How many issues should be open to be picked up?
featureDevelopmentIssuesWipLimit: 3
maintenanceIssuesWipLimit: 3

# How many attempts should be made to work on an issue?
attemptsPerBranch: 3
attemptsPerIssue: 3
