# Which agentic-lib workflow schedule should be used?
schedule: schedule-1

# Mapping for from symbolic keys to filepaths for access by agentic-lib workflows with limits and access permissions
paths:
  # Filepaths for elaborator workflows
  missionFilepath:
    path: MISSION.md
  librarySourcesFilepath:
    path: SOURCES.md
    limit: 16
    permissions:
      - write
  libraryDocumentsPath:
    path: elaborator-sandbox/library/
    limit: 8
    permissions:
      - write
  featuresPath:
    path: engineer-sandbox/features/
    limit: 3
    permissions:
      - write

  # Filepaths for engineer workflows
  contributingFilepath:
    path: CONTRIBUTING.md
  allTestsPaths:
    paths:
      - tests/unit/
      - engineer-sandbox/tests/
  targetTestsPath:
    path: engineer-sandbox/tests/
      - write
  allSourcePaths:
    paths:
      - src/lib/
      - engineer-sandbox/source/
      - write
  targetSourcePath:
    path: engineer-sandbox/source/
      - write
  dependenciesFilepath:
    path: package.json
  documentationPath:
    path: engineer-sandbox/docs/
      - write

  # Filepaths for maintainer workflows
  formattingFilepath:
    path: .prettierrc
  lintingFilepath:
    path: eslint.config.js
  readmeFilepath:
    path: README.md

# Execution commands
buildScript: npm run build
testScript: npm test
mainScript: npm run start

# How many issues should be available to be picked up?
featureDevelopmentIssuesWipLimit: 3
maintenanceIssuesWipLimit: 3

# How many attempts should be made to work on an issue?
attemptsPerBranch: 3
attemptsPerIssue: 3

# Web publishing
docRoot: public
