# Which agentic-lib workflow schedule should be used?
schedule: schedule-1

# Mapping for read-only filepaths
# These are used as defaults when invoking workflows
readOnlyFilepaths:
  mission:        "MISSION.md"
  contributing:   "CONTRIBUTING.md"
  dependencies:   "package.json"
  readme:         "README.md"
  formattingFile: ".prettierrc"
  lintingFile:    "eslint.config.js"

# Mapping for writeable filepaths
# These are used as defaults when invoking workflows and as allowed patterns for agents
writeableFilepaths:
  sources:  "SOURCES*.md"
  library:  "library/"
  features: "sandbox/features/"
  src:      "sandbox/source/"
  tests:    "sandbox/tests/"
  docs:     "sandbox/docs/"

# Execution commands
buildScript: "npm run build"
testScript: "npm test"
mainScript: "npm run start"

# How many sources should exist for document fetching?
sourcesLimit: 8

# How many documents should exist in the library?
documentsLimit: 16

# How many features should exist concurrently open for issue creation?
featuresWipLimit: 2

# TODO: Separate the concept of features in development and features in maintenance.
# How many issues should be open to be picked up?
featureDevelopmentIssuesWipLimit: 3
maintenanceIssuesWipLimit: 3

# How many attempts should be made to work on an issue?
attemptsPerBranch: 3
attemptsPerIssue: 3
