# .github/workflows/agent-archive-intentïon.yml
#
# This file is part of the example suite for `agentic-lib` see: https://github.com/xn-intenton-z2a/agentic-lib
# This file is licensed under the MIT License. For details, see LICENSE-MIT

name: archive-intentïon
concurrency: archive-intentïon
run-name: "archive intentïon"

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: false
  #schedule:
    #- cron: '49 8 */28 * *' # schedule-not-ready-1
    #- cron: '49 8,16 * * *' # schedule-not-ready-2
    #- cron: '49 */4 * * *' # schedule-not-ready-3
    #- cron: '49,34 * * * *' # schedule-not-ready-4

env:
  gitUserEmail: 'action@github.com'
  gitUserName: 'GitHub Actions[bot]'
  archivePath: 'archive/'

jobs:

  uuid:
    runs-on: ubuntu-latest
    steps:
      - id: uuid
        name: uuid
        shell: bash
        run: |
          uuid=$(uuidgen)
          echo "uuid: ${uuid}"
          echo "uuid=${uuid}" >> $GITHUB_OUTPUT
    outputs:
      uuid: ${{ steps.uuid.outputs.uuid }}

  agentic-lib:
    needs:
      - uuid
    uses: 'xn-intenton-z2a/agentic-lib/.github/workflows/wfr-agent-config.yml@main'
    with:
      configPath: ${{ vars.configPath || '.github/agents/agentic-lib.yml' }}
      haltSignal: "dont-halt-${{ needs.uuid.outputs.uuid }}"
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  intention:
    needs:
      - agentic-lib
      - uuid
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Get latest from remote
        run: |
          git config --local user.email "${{ env.gitUserEmail }}"
          git config --local user.name "${{ env.gitUserName }}"
          git pull --ff-only origin ${{ github.ref }}

      - name: intention
        id: intention
        uses: actions/github-script@v7
        env:
          seedDiscussionFilepath: ${{ needs.agentic-lib.outputs.seedDiscussionFilepath }}
          uuid: ${{ needs.uuid.outputs.uuid }}
        with:
          script: |
            const fs = require('fs');
            const { owner, repo } = context.repo;
            
            const uuid = process.env.uuid;
            const seedDiscussionFilepath = process.env.seedDiscussionFilepath;
            
            let branchUrl = ''; // branch URL
            try {
              core.info(`Looking for lines likely to be branches in intentïon.md at ${seedDiscussionFilepath}`);
        
              if (fs.existsSync(seedDiscussionFilepath)) {
                const seedDiscussionContent = fs.readFileSync(seedDiscussionFilepath, 'utf8');
                const lines = seedDiscussionContent.split('\n');
        
                // Filter to lines matching ^*https://.*/ some branch path fragments /*$ and extract the last matching line.
                const branchUrlPattern = /^\s*https:\/\/github\.com\/[^\/\s]+\/[^\/\s]+\/(tree|blob|edit|new|upload|commits)\/[^\s]+|https:\/\/github\.com\/[^\/\s]+\/[^\/\s]+\/compare\/[^.\/]+\.{3}[^\/\s]+/;                  
                const branchUrlLines = lines.filter(line => branchUrlPattern.test(line));
                if (branchUrlLines.length === 0) {
                  core.warning(`No matching GitHub branch URL found in intentïon.md`);
                } else {
                  const lastUrlLine = branchUrlLines[branchUrlLines.length - 1];
        
                  // Extract URL by ignoring anything before the first https:// and up to the first non-url character.
                  const urlMatch = lastUrlLine.match(/https:\/\/[^ ]+/);
                  if (urlMatch) {
                    branchUrl = urlMatch[0];
                    core.info(`Using URL from intentïon.md: ${url}`);
                  } else {
                    core.warning(`No matching GitHub branch URL found in intentïon.md: ${lastUrlLine}`);
                  }
                }
              } else {
                core.warning(`intentïon.md file not found at ${seedDiscussionFilepath}`);
              }
            } catch (error) {
              core.warning(`Error reading intentïon.md: ${error.message}`);
            }
  
            if(!branchUrl) {
              // Create a branch URL where the branch will be of the form intention-<date>-<uuid>
              const date = new Date().toISOString().split('T')[0];
              const branchName = `intention-${date}-${uuid}`;
              branchUrl = `https://github.com/${owner}/${repo}/tree/${branchName}`;
              core.info(`Created branch URL: ${branchUrl}`);
            }
            
            core.setOutput('branchUrl', branchUrl);
            core.info(`branchUrl: ${branchUrl}`);

  # Idempotently create the branch matching the branch URL if it doesn't exist or succeed silently if it does.
  create-branch:
    needs:
      - intention
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Get latest from remote
        run: |
          git config --local user.email "${{ env.gitUserEmail }}"
          git config --local user.name "${{ env.gitUserName }}"
          git pull --ff-only origin ${{ github.ref }}

      - name: create-branch-if-required-and-push
        id: create-branch-if-required-and-push
        run: |
          if [[ '${{ needs.intention.outputs.branchUrl }}' != *main' ]] ; then
            echo 'Creating or force pushing to branch: ${{ needs.intention.outputs.branchUrl }}'
            git switch --force-create '${{ needs.intention.outputs.branchUrl }}'
            git push -v --force origin '${{ needs.intention.outputs.branch }}'
          else
            echo 'Will not push to main looking target: ${{ needs.intention.outputs.branch }}'
          fi

  archive-intention:
    needs:
      - agentic-lib
      - intention
      - create-branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Get latest from remote
        run: |
          git config --local user.email "${{ env.gitUserEmail }}"
          git config --local user.name "${{ env.gitUserName }}"
          git pull --ff-only origin ${{ github.ref }}

      - name: Log seed in the intentïon file.
        run: |
          echo "" >> ${{ needs.agentic-lib.outputs.seedDiscussionFilepath }}
          echo "Arching intentïon to branch ${{ needs.intention.intention.branchUrl }} at $(date)" >> ${{ needs.agentic-lib.outputs.seedDiscussionFilepath }}

      - name: Commit and push
        id: commit
        continue-on-error: true
        run: |
          git config --local user.email '${{ env.gitUserEmail }}'
          git config --local user.name '${{ env.gitUserName }}'
          git status -v
          git add -v --all
          git diff
          git commit -m 'Reseed repository' --allow-empty
          git push -v
          git status -v

      - name: Push the current state of main to ${{ needs.agentic-lib.intention.branchUrl }}
        id: push-to-branch
        run: |
          git config --local user.email '${{ env.gitUserEmail }}'
          git config --local user.name '${{ env.gitUserName }}'
          git push -v origin HEAD:${{ needs.agentic-lib.intention.branchUrl }}
          git status -v