# .github/workflows/agent-source-to-library.yml
#
# This file is part of the example suite for `agentic-lib` see: https://github.com/xn-intenton-z2a/agentic-lib
# This file is licensed under the MIT License. For details, see LICENSE-MIT

name: agent-source-to-library
concurrency: agent-source-to-library
run-name: "agent-source-to-library"

on:
  workflow_dispatch:
  schedule:
    - cron: '15 4 */7 * *' # schedule-1
    #- cron: '15 4 * * *' # schedule-2
    #- cron: '15 */1 * * *' # schedule-3
    #- cron: '15 * * * *' # schedule-4

env:
  npmAuthOrganisation: ${{ vars.npmAuthOrganisation || '@xn-intenton-z2a' }}
  public: ${{ vars.public || 'public' }}
  s3BucketUrl: ${{ vars.s3BucketUrl || 's3://agentic-lib-telemetry-bucket/events/' }}
  s3WebsiteBucketUrl: ${{ vars.s3WebsiteBucketUrl || 's3://agentic-lib-public-website-stats-bucket/' }}
  iamActionsRoleArn: ${{ vars.iamActionsRoleArn || 'arn:aws:iam::541134664601:role/agentic-lib-github-actions-role' }}ยง
  iamStatsBucketWriterRoleArn: ${{ vars.iamStatsBucketWriterRoleArn || 'arn:aws:iam::541134664601:role/agentic-lib-deployment-role' }}
  iamPublicWebsiteStatsBucketWriterRoleArn: ${{ vars.iamPublicWebsiteStatsBucketWriterRoleArn || 'arn:aws:iam::541134664601:role/agentic-lib-public-website-stats-bucket-writer-role' }}

jobs:

  agentic-lib:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: agentic-lib
        id: agentic-lib
        shell: bash
        run: |
          if [ -f ".github/agentic-lib.yml" ]; then
            documentsLimit=$(grep '^documentsLimit:' .github/agentic-lib.yml | awk '{print $2}')
            if [ -z "$documentsLimit" ]; then
              documentsLimit="3"
              echo "Warning: documentsLimit not found in .github/agentic-lib.yml, using default value: ${documentsLimit}"
            fi

            # Extract library path from writeableFilepaths
            libraryDir=$(awk '/^writeableFilepaths:/,/^[^[:space:]]/ {if ($0 ~ /^[[:space:]]*library:/) print $2}' .github/agentic-lib.yml | sed 's/"//g')
            if [ -z "$libraryDir" ]; then
              libraryDir="library/"
              echo "Warning: library path not found in writeableFilepaths in .github/agentic-lib.yml, using default value: ${libraryDir}"
            fi

            # Extract sources path from writeableFilepaths
            sourcesFile=$(awk '/^writeableFilepaths:/,/^[^[:space:]]/ {if ($0 ~ /^[[:space:]]*sources:/) print $2}' .github/agentic-lib.yml | sed 's/"//g')
            if [ -z "$sourcesFile" ]; then
              sourcesFile="SOURCES*.md"
              echo "Warning: sources path not found in writeableFilepaths in .github/agentic-lib.yml, using default value: ${sourcesFile}"
            fi
          else
            documentsLimit="3"
            libraryDir="library/"
            sourcesFile="SOURCES*.md"
            echo "Warning: .github/agentic-lib.yml file not found, using default values: documentsLimit=${documentsLimit}, libraryDir=${libraryDir}, sourcesFile=${sourcesFile}"
          fi
          echo "documentsLimit=${documentsLimit}"
          echo "documentsLimit=${documentsLimit}" >> $GITHUB_OUTPUT
          echo "libraryDir=${libraryDir}"
          echo "libraryDir=${libraryDir}" >> $GITHUB_OUTPUT
          echo "sourcesFile=${sourcesFile}"
          echo "sourcesFile=${sourcesFile}" >> $GITHUB_OUTPUT

          # Extract writeable filepaths from writeableFilepaths values
          writeableFilepaths=$(awk '/^writeableFilepaths:/,/^[^[:space:]]/ {if ($0 ~ /^[[:space:]]*[a-zA-Z0-9_-]+:/) print $2}' .github/agentic-lib.yml | sed 's/"//g' | grep -v '^$' | jq -R . | jq -s .)
          echo "writeableFilepaths=${writeableFilepaths}"
          echo "writeableFilepaths=${writeableFilepaths}" >> $GITHUB_OUTPUT
    outputs:
      documentsLimit: ${{ steps.agentic-lib.outputs.documentsLimit }}
      libraryDir: ${{ steps.agentic-lib.outputs.libraryDir }}
      sourcesFile: ${{ steps.agentic-lib.outputs.sourcesFile }}
      writeableFilepaths: ${{ steps.agentic-lib.outputs.writeableFilepaths }}

  # If the document is "house choice", the repository will be assessed and an action chosen otherwise the supplied text will be used to generate a new document.
  maintain-library:
    needs:
      - agentic-lib
    permissions:
      contents: write
      issues: write
      id-token: write
    uses: 'xn-intenton-z2a/agentic-lib/.github/workflows/wfr-completion-maintain-library.yml@main'
    with:
      libraryDir: '${{ needs.agentic-lib.outputs.libraryDir }}'
      sourcesFile: '${{ needs.agentic-lib.outputs.sourcesFile }}'
      documentsLimit: '${{ needs.agentic-lib.outputs.documentsLimit }}'
      model: ${{ vars.CHATGPT_API_MODEL || 'o3-mini' }}
      npmAuthOrganisation: '@xn-intenton-z2a'
      gitUserEmail: 'action@github.com'
      gitUserName: 'GitHub Actions[bot]'
      writeableFilepaths: ${{ needs.agentic-lib.outputs.writeableFilepaths }}
    secrets:
      CHATGPT_API_SECRET_KEY: ${{ secrets.CHATGPT_API_SECRET_KEY }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  select-issue:
    permissions:
      issues: read
      id-token: write
    uses: 'xn-intenton-z2a/agentic-lib/.github/workflows/wfr-github-select-issue.yml@main'
    with:
      issueNumber: ''
      selectionLabel: 'automated'
    secrets:
      CHATGPT_API_SECRET_KEY: ${{ secrets.CHATGPT_API_SECRET_KEY }}

  stats:
    needs:
      - select-issue
      - maintain-library
    if: ${{ always() }}
    permissions:
      contents: write
      id-token: write
      pages: write
    uses: 'xn-intenton-z2a/agentic-lib/.github/workflows/wfr-github-stats-to-aws.yml@main'
    with:
      cache: 'npm'
      npmAuthOrganisation: "${{ vars.npmAuthOrganisation || '@xn-intenton-z2a' }}"
      lastActivityName: "${{ github.workflow }}"
      lastActivityBranchName: "${{ github.ref_name }}"
      nextIssue: "[${{ needs.select-issue.outputs.issueNumber }}] ${{ needs.select-issue.outputs.issueTitle }} ${{ needs.select-issue.outputs.issueLabels }}"
      public: 'public'
      s3BucketUrl: "${{ vars.s3BucketUrl || 's3://agentic-lib-telemetry-bucket/events/' }}"
      s3WebsiteBucketUrl: "${{ vars.s3WebsiteBucketUrl || 's3://agentic-lib-public-website-stats-bucket/' }}"
      iamActionsRoleArn: "${{ vars.iamActionsRoleArn || 'arn:aws:iam::541134664601:role/agentic-lib-github-actions-role' }}"
      iamStatsBucketWriterRoleArn: "${{ vars.iamStatsBucketWriterRoleArn || 'arn:aws:iam::541134664601:role/agentic-lib-deployment-role' }}"
      iamPublicWebsiteStatsBucketWriterRoleArn: "${{ vars.iamPublicWebsiteStatsBucketWriterRoleArn || 'arn:aws:iam::541134664601:role/agentic-lib-public-website-stats-bucket-writer-role' }}"
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
