# .github/workflows/automerge-on-pull-request.yml
name: Automerge on Pull Request
concurrency: automerge-${{ github.ref_name }}
run-name: "Automerge on Pull Request [${{ github.ref_name }}]"

on:
  pull_request:
    types:
      - labeled
      - reopened
      - synchronize

jobs:

  check-pr:
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    permissions:
      contents: write
      pull-requests: write
    uses: './.github/workflows/wfr-automerge-check-pr-and-merge.yml'
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  label-issue-after-check-pr:
    needs:
      - check-pr
    if: needs.check-pr.outputs.prMerged == 'true' && needs.check-pr.outputs.pullNumber != ''
    permissions:
      contents: write
      pull-requests: write
    uses: './.github/workflows/wfr-automerge-label-issue.yml'
    with:
      pullNumber: '${{ needs.check-pr.outputs.pullNumber }}'
      branchPrefix: 'issue-'
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  wait-for-merge:
    needs:
      - check-pr
    if: needs.check-pr.outputs.shouldSkipMerge != 'true'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Sleeping for 60 seconds."
        shell: bash
      - run: sleep 60
        shell: bash

  automerge:
    needs:
      - check-pr
      - wait-for-merge
    if: needs.check-pr.outputs.shouldSkipMerge != 'true'
    permissions:
      contents: write
      pull-requests: write
    uses: './.github/workflows/wfr-automerge-merge-pr.yml'
    with:
      pullNumber: '${{ needs.check-pr.outputs.pullNumber }}'
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  label-issue-after-automerge:
    needs:
      - check-pr
      - automerge
    if: needs.automerge.outputs.prMerged == 'true' && needs.check-pr.outputs.pullNumber != ''
    permissions:
      contents: write
      #pull-requests: write
    uses: './.github/workflows/wfr-automerge-label-issue.yml'
    with:
      pullNumber: '${{ needs.check-pr.outputs.pullNumber }}'
      branchPrefix: 'issue-'
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
