# .github/workflows/automerge-on-check-suite.yml
name: Automerge on Check Suite
concurrency: automerge-${{ github.ref_name }}
run-name: "Automerge on Check Suite [${{ github.ref_name }}]"

on:
  check_suite:
    types:
      - completed

jobs:

  check-pr:
    if: github.event.check_suite.conclusion == 'success'
    permissions:
      contents: write
      pull-requests: write
    uses: './.github/workflows/wfr-automerge-find-pr-in-check-suite.yml'
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  label-issue-after-check-pr:
    needs:
      - check-pr
    if: needs.check-pr.outputs.prMerged == 'true' && needs.check-pr.outputs.pullNumber != ''
    permissions:
      contents: write
      pull-requests: write
    uses: './.github/workflows/wfr-automerge-label-issue.yml'
    with:
      pullNumber: '${{ needs.check-pr.outputs.pullNumber }}'
      branchPrefix: 'issue-'
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  automerge:
    needs:
      - check-pr
    if: needs.check-pr.outputs.shouldSkipMerge != 'true'
    permissions:
      contents: write
      pull-requests: write
    uses: './.github/workflows/wfr-automerge-merge-pr.yml'
    with:
      pullNumber: '${{ needs.check-pr.outputs.pullNumber }}'
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  label-issue-after-automerge:
    needs:
      - check-pr
      - automerge
    if: needs.automerge.outputs.prMerged == 'true' && needs.check-pr.outputs.pullNumber != ''
    permissions:
      contents: write
      #pull-requests: write
    uses: './.github/workflows/wfr-automerge-label-issue.yml'
    with:
      pullNumber: '${{ needs.check-pr.outputs.pullNumber }}'
      branchPrefix: 'issue-'
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
