# .github/workflows/automerge.yml
name: Automerge
concurrency: branch-main
run-name: "Automerge [${{ github.ref_name }}]"

on:
  pull_request:
    types:
      - labeled
      - reopened
      - synchronize
  check_suite:
    types:
      - completed
  workflow_dispatch:
    inputs:
      pullNumber:
        description: 'The pull request number to review. e.g. "123"'
        required: false
        type: string
        default: ''
  schedule:
    # Run every 10 minutes (as an example)
    #- cron: '*/10 * * * *'
    - cron: '15 */2 * * *'

jobs:
  check-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Determine pull request number
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
        id: determine-pr
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let pullNumber = core.getInput('pullNumber');
            if (!pullNumber) {
              const { data: pullRequests } = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                per_page: 1,
                sort: 'created',
                direction: 'asc'
              });
              if (pullRequests.length > 0) {
                pullNumber = pullRequests[0].number;
              } else {
                core.setFailed('No open pull requests found.');
              }
            }
            core.setOutput('pullNumber', pullNumber);

      - name: Run pull_request check
        if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'automerge')
        id: pr
        uses: './.github/workflows/wfr-automerge-check-pr-and-merge.yml'

      - name: Run check_suite check
        if: github.event_name == 'check_suite' && github.event.check_suite.conclusion == 'success'
        id: cs
        uses: './.github/workflows/wfr-automerge-find-pr-in-check-suite.yml'

      - name: set-outputs
        id: set-outputs
        uses: actions/github-script@v6
        with:
          script: |
            let prMerged = '';
            let pullNumber = '';
            let shouldSkipMerge = '';
            if (steps.pr && steps.pr.outputs && steps.pr.outputs.pullNumber) {
              console.log("Using pull_request outputs");
              prMerged = steps.pr.outputs.prMerged;
              pullNumber = steps.pr.outputs.pullNumber;
              shouldSkipMerge = steps.pr.outputs.shouldSkipMerge;
            } else if (steps.cs && steps.cs.outputs && steps.cs.outputs.pullNumber) {
              console.log("Using check_suite outputs");
              prMerged = steps.cs.outputs.prMerged;
              pullNumber = steps.cs.outputs.pullNumber;
              shouldSkipMerge = steps.cs.outputs.shouldSkipMerge;
            } else {
              console.log("Using determine-pr outputs");
              prMerged = 'false';
              pullNumber = steps.determine-pr.outputs.pullNumber;
              shouldSkipMerge = 'false';
            }
            return { prMerged, pullNumber, shouldSkipMerge };
          result-encoding: string
    outputs:
      prMerged: ${{ steps.set-outputs.outputs.prMerged }}
      pullNumber: ${{ steps.set-outputs.outputs.pullNumber }}
      shouldSkipMerge: ${{ steps.set-outputs.outputs.shouldSkipMerge }}

  label-issue-after-check-pr:
    needs:
      - check-pr
    if: needs.check-pr.outputs.prMerged == 'true' && needs.check-pr.outputs.pullNumber != ''
    permissions:
      contents: write
      pull-requests: write
    uses: './.github/workflows/wfr-automerge-label-issue.yml'
    with:
      pullNumber: '${{ needs.check-pr.outputs.pullNumber }}'
      branchPrefix: 'issue-'

  wait-for-merge:
    needs:
      - check-pr
    if: needs.check-pr.outputs.shouldSkipMerge != 'true'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Sleeping for 60 seconds."
        shell: bash
      - run: sleep 60
        shell: bash

  automerge:
    needs:
      - check-pr
      - wait-for-merge
    if: needs.check-pr.outputs.shouldSkipMerge != 'true'
    permissions:
      contents: write
      pull-requests: write
    uses: './.github/workflows/wfr-automerge-merge-pr.yml'
    with:
      pullNumber: '${{ needs.check-pr.outputs.pullNumber }}'

  label-issue-after-automerge:
    needs:
      - check-pr
      - automerge
    if: needs.automerge.outputs.prMerged == 'true' && needs.check-pr.outputs.pullNumber != ''
    permissions:
      contents: write
      issues: write
    uses: './.github/workflows/wfr-automerge-label-issue.yml'
    with:
      pullNumber: '${{ needs.check-pr.outputs.pullNumber }}'
      branchPrefix: 'issue-'