# .github/workflows/issue-for-linting.yml
name: Linting
concurrency: branch-${{ github.ref_name }}
run-name: "Linting [${{ github.ref_name }}]"

on:
  workflow_dispatch:
  schedule:
    - cron: '15 4 * * *' # Run every day at 4:15

jobs:

  linting:
    permissions:
      contents: write
      packages: write
      id-token: write
    uses: 'xn-intenton-z2a/agentic-lib/.github/workflows/wfr-run-script-and-commit-to-branch.yml@main'
    with:
      script: 'npm run formatting -- "." ; npm run linting "." -- --max-warnings=10'
      sarifScript: 'npm run linting-json --silent'
      testScript: 'npm test'
      branch: 'apply-formatting'
      gitUserEmail: 'action@github.com'
      gitUserName: 'GitHub Actions[bot]'
      gitCommitMessage: 'Updated by `npm run formatting-fix -- "." ; npm run linting-fix "." -- --max-warnings=10`'

  create-issue:
    needs:
      - linting
    if: ${{ needs.linting.outputs.fixRequired == 'true' && needs.linting.outputs.resultsCount != '0' }}
    permissions:
      issues: write
      id-token: write
    uses: 'xn-intenton-z2a/agentic-lib/.github/workflows/wfr-create-issue.yml@main'
    with:
      issueTitle: 'Resolve issues in output from running: npm run formatting-fix -- "." ; npm run linting-fix "." -- --max-warnings=10'
      issueBody: ${{ needs.linting.outputs.scriptOutput }}
