# .github/workflows/linting.yml
name: 4. Linting
run-name: "Linting [${{ github.ref_name }}]"
concurrency: linting-${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      runWorker:
        description: 'true, if the worker should be run.'
        required: false
        type: boolean
        default: true
  schedule:
    # Nightly check and uplift: 0:00 test, 3:15 formatting, 3:30 linting
    - cron: '30 3 * * *'
    # Regular agitations: 2am, 8am, 2pm, 8pm with a linting check shortly after
    #- cron: '5 2,8,14,20 * * *'
    #- cron: '0 * * * *'

jobs:

  check-linting:
    permissions:
      contents: write
    uses: './.github/workflows/wfr-run-sarif-script-then-post-script-and-push-changes.yml'
    with:
      sarifScript: 'npx --silent eslint --fix --format=@microsoft/eslint-formatter-sarif ./src/ ./tests/'
      postScript: 'prettier --write ./src/ ./tests/'
      testScript: 'npm test'
      baseDir: './src/ ./tests/'
      logToFilepath: './intention-log.json'
      npmAuth: 'true'
      gitUserEmail: 'action@github.com'
      gitUserName: 'GitHub Actions[bot]'
      gitCommitMessage: "Updated by: apply-fixes-sarif"
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linting-fix-not-required:
    needs:
      - check-linting
    if: ${{ needs.check-linting.outputs.fixRequired == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Done."

  create-fix-intention:
    needs:
      - check-linting
    if: ${{ needs.check-linting.outputs.fixRequired == 'true' }}
    permissions:
      contents: write
      packages: write
      id-token: write
    uses: './.github/workflows/wfr-create-intention.yml'
    with:
      branchPrefix: 'issue-'
      testScript: 'npm test'
      npmAuth: 'true'
      gitUserEmail: 'action@github.com'
      gitUserName: 'GitHub Actions[bot]'
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  runLintingWorker:
    runs-on: ubuntu-latest
    needs:
      - create-fix-intention
    if: ${{ needs.check-linting.outputs.fixRequired == 'true' }}
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Trigger linting-worker workflow
        if: ${{ inputs.runWorker == true }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'linting-worker.yml',
              ref: context.ref,
              inputs: {} 
            });
