# .github/workflows/stats.yml
#
# This file is part of the example suite for `agentic-lib` see: https://github.com/xn-intenton-z2a/agentic-lib
# This file is licensed under the MIT License. For details, see LICENSE-MIT

name: ∞ Stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *' # schedule-1
    #- cron: '*/15 * * * *' # schedule-2
    #- cron: '*/5 * * * *' # schedule-3

jobs:
  stats:
    permissions:
      contents: write
      id-token: write
      pages: write
    uses: 'xn-intenton-z2a/agentic-lib/.github/workflows/wfr-github-stats.yml@main'
    with:
      cache: 'npm'
      public: 'public'
      s3BucketUrl: 's3://agentic-lib-bucket/events/'
      iamActionsRoleArn: 'arn:aws:iam::541134664601:role/agentic-lib-github-actions-role'
      iamDeploymentRoleArn: 'arn:aws:iam::541134664601:role/agentic-lib-deployment-role'
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}