# .github/workflows/test.yml
name: 3. Tests
run-name: 'Tests [${{ github.ref_name }}] [${{ github.event.head_commit.message }}]'

on:
  push:
    paths:
      - '**/*.sh'
      - '**/*.js'
      - '**/*.json'
      - '**/*.yml'
      - '**/*.properties'
      - '!exports/**'
  workflow_dispatch:
  schedule:
    # Test every 6 hours
    - cron: '0 4,10,16,22 * * *'

jobs:

  npm-test:
    name: 'npm test with coverage'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: pwd
      - run: ls -l
      - run: find . -name '*.js' -exec echo '{}' \; | grep -v 'node_modules'
      - run: npm test

  run-action:
    name: 'run-action tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: resolve
        id: resolve
        uses: 'polycode-projects/apply-fixes-sarif@main'
        with:
          resultsToResolve: '1'
          iterations: '1'
          programFitnessCommand: 'npx prettier --write  ./src/ ./tests/ > /dev/null 2>&1 || true ; npx --silent eslint --fix --format=@microsoft/eslint-formatter-sarif ./src/ ./tests/'
          # programFitnessCommand: 'npx --silent eslint --fix --format=@microsoft/eslint-formatter-sarif ./tests/unit/module-index.test.js'
          # programFitnessCommand: 'npx --silent eslint --fix --format=@microsoft/eslint-formatter-sarif ./src/lib/string-transformers.js'
          # programFitnessCommand: 'npx --silent eslint --config eslint-txt.config.js --fix --format=@microsoft/eslint-formatter-sarif src/examples/example-sonarjs-pseudo-random.original.txt'
          baseDir: './'
        env:
          CHATGPT_API_SECRET_KEY: ${{ secrets.CHATGPT_API_SECRET_KEY }}
          I7N_SAFETY_PROTOCOLS: 'off'
          CACHE_ENABLED: 'true'
          CACHE_FILEPATH: './prompt-cache.jsonl'
          ACTIONS_STEP_DEBUG: 'true'
          LOG_LEVEL: 'info'
          LOG_TO_CONSOLE: 'true'
          LOG_TO_FILEPATH: './intention-log.jsonl'
      - name: console-logger after resolve
        shell: bash
        run: |
          cat <<EOF
          ${{ steps.resolve.outputs.resolution }}
          EOF
          cat <<EOF
          ${{ steps.resolve.outputs.fixedProgramFilepathsChanged }}
          EOF
      - run: ls -l './intention-log.jsonl' && wc -l './intention-log.jsonl' || echo 'missing ./intention-log.jsonl'
      - run: |
          git config --local user.email 'action@github.com' \
          && git config --local user.name 'GitHub Actions[bot]' \
          && git status -v \
          ;
      - name: Upload Logging Output
        uses: actions/upload-artifact@v4
        with:
          name: intention-log
          path: './intention-log.jsonl'
