# .github/workflows/update.yml
name: 7. Update
run-name: "Update [${{ github.ref_name }}]"

on:
  repository_dispatch:
    # This triggers whenever we receive a repository_dispatch event named 'package-published'
    types: [package-published]
  schedule:
    # Nightly updates: 7am update
    - cron: '30 7 * * *'
  workflow_dispatch:
    inputs:
      upgradeTarget:
        description: 'Select the type of update to run'
        type: choice
        default: 'minor'
        required: false
        options:
          - greatest
          - latest
          - newest
          - patch
          - minor
          - semver

jobs:
  update-dependencies:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    uses: './.github/workflows/wfr-update.yml'
    with:
      deleteAllCaches: 'true'
      buildScript: 'npm run build'
      testScript: 'npm test'
      mainScript: 'node src/lib/main.js'
      upgradeTarget: ${{ inputs.upgradeTarget || 'patch' }}
      gitUserEmail: 'action@github.com'
      gitUserName: 'GitHub Actions[bot]'
      gitCommitMessage: 'chore: dependency updates'
    secrets:
      # PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

