# .github/workflows/wfr-github-merge-pr.yml

#
# agentic-lib
# Copyright (C) 2025 Polycode Limited
#
# This file is part of agentic-lib.
#
# agentic-lib is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License v3.0 (GPL‑3).
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# IMPORTANT: Any derived work must include the following attribution:
# "This work is derived from https://github.com/xn-intenton-z2a/agentic-lib"
#

name: ∞ automerge-merge-pr

on:
  workflow_call:
    inputs:
      pullNumber:
        description: 'The pull request number. e.g. "123"'
        type: string
        required: true
      cache:
        description: 'The cache to use for npm. e.g. "npm"'
        type: string
        required: false
        default: 'npm'
      s3BucketUrl:
        description: 'The S3 bucket URL with prefix to use. e.g. "s3://my-bucket/prefix"'
        type: string
        required: false
        default: ''
      iamRoleArn:
        description: 'The ARN of the IAM role to assume. e.g. "arn:aws:iam::123456789012:role/my-role"'
        type: string
        required: false
        default: ''
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: false
    outputs:
      prMerged:
        description: 'Set to "true", if the PR has been merged either already or by this process.'
        value: ${{ jobs.merge-pr.outputs.prMerged }}

jobs:
  merge-pr:
    runs-on: ubuntu-latest

    env:
      cache: ${{ inputs.cache || 'npm' }}
      s3BucketUrl: ${{ inputs.s3BucketUrl || '' }}
      iamRoleArn: ${{ inputs.iamRoleArn || '' }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: ${{ env.cache }}

      - name: Set up .npmrc
        shell: bash
        run: |
          echo "${{ env.npmAuthOrganisation }}:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PERSONAL_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}" >> .npmrc
          echo "always-auth=true" >> .npmrc

      - name: trigger-checks
        id: trigger-checks
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
          script: |
            const pullNumber = parseInt('${{ inputs.pullNumber }}', 10);
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            // Get the latest PR information
            const { data: pullRequest } = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: pullNumber,
            });
            core.info(`Found pull request #${pullRequest.number} with state: ${pullRequest.state} and mergeable state: ${pullRequest.mergeable_state}`);
            core.info(`PR: ${JSON.stringify(pullRequest)}`);
            
            let mergeable = pullRequest.mergeable;
            if (pullRequest.state === "closed") { 
              core.info(`PR #${pullNumber} is already closed.`);
            } else if (mergeable === null) {
              core.info(`PR #${pullNumber} does not yet have a value for mergeability, triggering checks.`);
              const ref = pullRequest.head.sha;
              const { data: checkSuites } = await github.rest.checks.listSuitesForRef({
                owner,
                repo,
                ref
              });
              core.info(`PR check suites: ${JSON.stringify(checkSuites)}`);
              for (const suite of checkSuites.check_suites) {
                try{ 
                  await github.rest.checks.rerequestSuite({
                    owner,
                    repo,
                    check_suite_id: suite.id
                  });
                } catch (error) {
                  core.info(`Failed to trigger check suite for PR #${pullNumber}: ${error.message}`);
                  core.info(`${JSON.stringify(error)}`);
                }
              }
            } else {
              core.info(`PR #${pullNumber} is in mergeable state ${mergeable}.`);
            }
            
            core.setOutput('mergeable', mergeable);
            core.info(`mergeable: '${mergeable}'`);

      - name: Wait for 5 seconds
        run: sleep 5

      - name: auto-merge-pr
        id: auto-merge-pr
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
          script: |
            const pullNumber = parseInt('${{ inputs.pullNumber }}', 10);
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            let prMerged;
          
            // Get the latest PR information
            const { data: pullRequest } = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: pullNumber,
            });
            core.info(`Found pull request #${pullRequest.number} with state: ${pullRequest.state} and mergeable state: ${pullRequest.mergeable_state}`);
          
            if (pullRequest.state === "closed") { 
              core.info(`PR #${pullNumber} is already closed.`);
              if (pullRequest.merged) {
                core.info(`PR #${pullNumber} is closed and merged.`);
                prMerged = 'true';
              } else {
                core.info(`PR #${pullNumber} is closed but not merged.`);
                prMerged = 'false';
              }
            } else if (pullRequest.mergeable && pullRequest.mergeable_state === 'clean') {
              // If the PR is mergeable (clean), proceed with merging
              await github.rest.pulls.merge({
                owner,
                repo,
                pull_number: pullNumber,
                merge_method: 'squash',
              });
              core.info(`PR #${pullNumber} merged successfully.`);
              const branchRef = `heads/${pullRequest.head.ref}`;
              await github.rest.git.deleteRef({
                owner,
                repo,
                ref: branchRef,
              });
              core.info(`Branch '${pullRequest.head.ref}' deleted.`);
              prMerged = 'true';
            } else if (pullRequest.mergeable_state === 'dirty' || pullRequest.mergeable === false) {
              // PR has conflicts or failing tests – close the PR and delete the branch
              core.info(`PR #${pullNumber} has conflicts. Commenting on the PR and closing it.`);
              await github.rest.issues.createComment({
                  owner,
                  repo,
                  issue_number: pullNumber,
                  body: `This pull request is being closed due to conflicts (mergeable_state: ${pullRequest.mergeable_state}, mergeable: ${pullRequest.mergeable}).`,
                });
              await github.rest.pulls.update({
                owner,
                repo,
                pull_number: pullNumber,
                state: "closed",
              });
              const branchRef = `heads/${pullRequest.head.ref}`;
              try {
                await github.rest.git.deleteRef({
                  owner,
                  repo,
                  ref: branchRef,
                });
                core.info(`Branch '${pullRequest.head.ref}' deleted.`);
              } catch (error) {
                core.warning(`Failed to delete branch '${pullRequest.head.ref}': ${error.message}`);
              }
              prMerged = 'false';
            } else if (pullRequest.mergeable === null) {
              core.info(`PR #${pullNumber} does not yet have a value for mergeability.`);
              prMerged = 'false';
            } else {
              core.info(`PR #${pullNumber} is in an unexpected state.`);
              prMerged = 'false';
            }
          
            core.setOutput('prMerged', prMerged);
            core.info(`prMerged: '${prMerged}'`);

    outputs:
      prMerged: ${{ steps.auto-merge-pr.outputs.prMerged }}

